services:
  postgres:
    image: postgres:15
    container_name: reachinbox-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: reachinbox-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
